# Generated by Django 5.0.2 on 2024-02-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_22', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktypes',
            name='for_counter',
            field=models.IntegerField(default=0),
        ),
    ]
