# Generated by Django 4.2.5 on 2023-09-26 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(max_length=50)),
                ('surname', models.TextField(max_length=50)),
                ('name', models.TextField(max_length=50)),
                ('patronymic', models.TextField(max_length=50)),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('imageSource', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrintOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=50)),
                ('dateCreate', models.DateTimeField()),
                ('dateForm', models.DateTimeField()),
                ('dateEnd', models.DateTimeField()),
                ('service', models.ManyToManyField(to='fablab_backend.worktypes')),
                ('userData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fablab_backend.participants')),
            ],
        ),
    ]
