# Generated by Django 4.2.5 on 2023-09-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fablab_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="participants",
            table="Participants",
        ),
        migrations.AlterModelTable(
            name="printorders",
            table="Printorders",
        ),
        migrations.AlterModelTable(
            name="worktypes",
            table="Worktypes",
        ),
    ]
