# Generated by Django 4.2.5 on 2023-09-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fablab_backend",
            "0002_alter_participants_table_alter_printorders_table_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="participants",
            table="participants",
        ),
        migrations.AlterModelTable(
            name="printorders",
            table="printorders",
        ),
        migrations.AlterModelTable(
            name="worktypes",
            table="worktypes",
        ),
    ]
